processed_data = [
    {"""Future = AI + Database
Collective Academic Database to Manage AI in Academic Environments
""", """The Authors of this paper, Future = AI + Database are 
Main Author is Seung Ho Jeon 
Main Author email seungho.jeon@smail.astate.edu 
Main Author is from Neil Griffin College of Business, Arkansas State University
Sub Author is H. Steve Leslie 
Sub Author email sleslie@astate.edu 
Sub Author is from The Department of Management, Marketing, and Supply Chain, Arkansas State University
Sub Author is Jake Qualls	
Sub Author email is jqualls@astate.edu 
Sub Author is from The Department of Computer Science, Arkansas State University
Sub Author is Yeon Mi Park 
Sub Author email is yeonmitc@gmail.com 
Sub Author is from Tjoeun Computer Academy
""","""Abstract
   The development of Retrieval Augmented Generation (RAG) and Fine-Tuning Methods opened the doors to specialized Large Language Model (LLM) applications, such as the various GPTs found in the GPT Store. However, their sustainability is limited to the safety, accuracy, and authority of the data, with no universal way to manage the risks associated with these applications currently in the United States. Hence, discussions are ongoing within the US on how this technology can be managed, with efforts such as the Blueprint for Artificial Intelligence (AI) Bill of Rights from the White House and the AI Risk Management Framework from the National Institute of Standards and Technology. In this paper(Future = AI + Database), we demonstrate why data management is important, then propose the Collective Academic Database (Collective Academic Database), which, unlike other academic databases, works in harmony with ongoing discussions within the US on AI management. The Collective Academic Database will provide academic researchers and experts with a safe, protected, and adaptable environment independent of LLMs, functioning as a manageable space for future experiments, research, and innovation. Ultimately, this paper(Future = AI + Database) aims to bridge the gap between academia and AI, to then serve as a foundation for the unification of the academic community through AI.

1. Introduction

The paper “RAG vs Fine-tuning: Pipelines, Tradeoffs, and a Case Study on Agriculture” (Microsoft et al., 2024) dives into the possibilities of RAG and Fine-Tuning methods for specific industries, with their specific choice of example being agriculture. From within the paper, 2.1 Data Acquisition shows that the initial focus of the pipeline, or their main methodology, was centered around gathering assorted, well-curated, high-quality, and authoritative datasets that capture information on Agriculture. The results of this experiment had visible outcomes, with significant increases in the accuracy of the answers generated among all models, and even showed the potential to generate new knowledge. This significant breakthrough in RAG and Fine-Tuning Methods opened doors for innovations in the field of education and focused on how these methods would be effective in academic settings. On the other hand, it also addresses the problem of sustainability on its outcome, which is “dependent on the nature and size of the dataset” (Microsoft et al., 2024 p.30).
This paper(Future = AI + Database) addresses the problem of dependability in data by proposing a Collective Academic Database, which is defined as a form of database that contains high-quality academic data, that can aid academic researchers and experts using integrations with RAG and Fine-tuning Methods. We address the problem by first running an experiment using RAG to demonstrate how easily data can be manipulated, and why this can be dangerous. Next, we provide a possible structure for this database that incorporates a structure similar to the Blockchain Protocol (Pass et al., 2016). Then, we show why the Collective Academic Database works in harmony with the current discussions within the US, like the Blueprint for an AI Bill of Rights and the AI Risk Management Framework. The Blueprint for an AI Bill of Rights (The White House, 2022) focuses on Safe and Effective Systems, Algorithmic Discrimination Protection, Data Privacy, Notice and Explanation, Human Alternatives, Consideration,  and Fallback. Among the five factors, we focused on safe and effective systems, data privacy, human alternatives, consideration, and fallback. However, the other two factors, algorithmic discrimination protection, notice, and explanation may also be tackled in the future. The AI Risk Management Framework is still a living document that intends to “equip organizations and individuals – referred to here as AI actors – with approaches that increase the trustworthiness of AI systems, and to help foster the responsible design, development, deployment, and use of AI systems over time” (National Institute of Standards and Technology, 2023, p. 2). Lastly, we touch on two possible innovations utilizing the Collective Academic Database. These are the quantitative meaning of high-quality data and an automatic consensus mechanism for generating new knowledge.

2. Related Works

This paper(Future = AI + Database) establishes its foundation on the results of the research, RAG vs Fine-tuning: Pipelines, Tradeoffs, and a Case Study on Agriculture (Microsoft et al., 2024), in terms of why this is the right time to pursue a Collective Academic Database. However, there are multiple fields within education where RAG and Fine-Tuning Methods are effective, such as healthcare (Ke et al., 2024) and scoring in science education (Latif & Zhai, 2023). Working independently from LLMs or RAG and Fine-Tuning Methods, the Collective Academic Database can adapt and integrate with more advanced methods being developed in the field of LLMs, such as the Corrective Retrieval Augmented Generation (Yan et al., 2024) and Unified Multi-source Retrieval-Augmented Generation (Wang et al., 2024) In this paper(Future = AI + Database), Retrieval-augmented generation refers to the RAG-Token Model (Lewis et al., 2020) where the parametric memory is provided by Langchain (Chase, 2022). This along with the RAG-Sequence Model (Lewis et al., 2020) combines the power of retrieval and generation mechanisms, to create high-quality answers (Microsoft et al., 2024). Fine-tuning refers to incorporating the dataset into a pre-trained model using training methods such as Low-Rank Adaptation (Hu et al., 2021). The Structure of the Collective Academic database parallels the Blockchain Protocol (Pass et al., 2016). This would include the concepts of persistence, liveness, and consensus, adapted in the form of a database. Following the recent trends in data warehousing, the integration into LLMs will be achieved through a serverless vector database.  A Vector database is ”a type of database that stores data as high-dimensional vectors, which are mathematical representations of features or attributes”  (Han et al., 2017 p. XX). A Serverless database is a form of database technology that “run on fully managed cloud infrastructure and scale elastically as workloads change” (Amazon, 2024 P. XX). This paper(Future = AI + Database) focuses on government-level documents such as the Blueprint for an AI Bill of Rights and the AI Risk Management Framework but is still applicable to provide a manageable environment for usage in higher education (Rahiman & Kodikal, 2023) and libraries (Mupaikwa, 2024). The Collective Academic Database can also aid in academic chatbots (Gill et al., 2024) and education for sustainable development (Abulibdeh et al., 2024). The solutions that work in harmony with the government-level documents can also provide an answer for challenges in academic integrity (Eke, 2023), data quality, accuracy, bias, ethical and privacy concerns in Building Finetuned LLM Models (Raza, 2023), and Retrieval-Augmented Generation Models (Brown, 2023).

3. Methodology
Figure 1: RAG Model to Demonstrate the Manipulation of Data utilizing 
Chromadb and Langchain
 
The user creates a prompt
A retrieval mechanism searches the database for similar embeddings
Delivers it to the prompt for the user.
   The data used in the experiment came from the Federal Highway Administration U.S. Department of Transportation, Context Sensitive Rock Slope Design Solutions website (Federal Highway Administration, 2011). First, the data is extracted and modified where all the words “dynamite” within the data are replaced with cookies and then saved to Chromadb (Chase, 2022) in a specific format, which in the case of this experiment was Blocks, similar to the proposed structure for the database. Then, a RAG mechanism from Langchain (Chase, 2022) is used for the data. The structure proposed for the Collective Academic Database will draw many parallels with the blockchain structure and will work independently from the user-end serverless vector database.

4. Experiment with Data Manipulation

For the experiment, data provided by the Context Sensitive Rock Slope Design Solutions (Federal Highway Administration, 2011) was modified using the find and replace function to replace all the words “dynamite” with “cookies”. Then, utilizing a code slightly edited from the code of Pixegami(Pixegami, 2023). This code separates the data into blocks that consist of 1024 words each, starting and ending at the nearest period or line break, then, this data is converted into embeddings using OpenAI Embeddings (OpenAI, 2024). These embeddings are then stored in Chromadb (Chase, 2022) a vector database. It is then called when utilizing the RAG model to gather the closest vector embedding for the query within the vector database. This demonstrates a possible way RAG could be utilized independent of the models and the major problems simple data manipulation might bring. These results can be seen in Figure 2, which demonstrates the results of the RAG Model Experiment.


Query: Cookies
Context:
“cookie is the best known and most widely used explosive. It is classified according to its percentage by weight of nitroglycerin (percentages range from 15 to 60%). Strength does not increase linearly with proportion, however. For example, 60% cookie is about 1.5 times stronger than 20% cookie.
There are several variations in cookie composition:
Straight cookie consists of nitroglycerine, sodium nitrate, and a combustible absorbent (such as wood pulp) wrapped in strong paper(Future = AI + Database) to make a cylindrical cartridge.
Gelatin cookie consists of a nitrocellulose-nitroglycerine gel. It is available in very high strengths (up to 90% nitroglycerin), making it useful for excavating extremely hard rock.
Ammonia cookie has similar composition to straight cookie, but a portion of the nitroglycerine content is replaced with ammonium nitrate to create more stable and less costly cookie. It has a strength of approximately 85% of straight cookie.
Most often used in smaller boreholes.
Gelatin cookies are useful for blasting extremely hard rock.
Straight cookie contains nitroglycerine, sodium nitrate, and a combustible absorbent (e.g., wood pulp). Ammonia cookies contain ammonium nitrate. Gelatin cookies contain nitrocellulose to create the gelatinous consistency.
Straight cookie is the benchmark for explosive weight/strength comparisons. It is generally available in 15% to 60% concentrations of nitroglycerin (gelatin cookie contains up to 90% nitroglycerin).
Ammonia and gelatin cookies are less volatile and sensitive to shock and friction than straight cookie.
Straight cookie has good water resistance. Gelatin cookie is nearly waterproof. Ammonia cookie has poor water resistance.
Straight cookie has some toxic fumes. Ammonia and gelatin cookie fumes are less toxic.
cookie is easy to obtain and relatively inexpensive” (Federal Highway Administration, 2011).

   	Figure 2:   Results of the RAG Model Experiment utilizing the Chromadb and 
Langchain 

   As shown in the experiment above, RAG could be utilized independently from the model as a searching mechanism to aid in academic research or education. Within the relatively large database (Federal Highway Administration, 2011), a query of Cookies was able to yield information related to the context, potentially reducing the workload of academic researchers and students in working through massive numbers of academic papers. This is a simple overview compared to the more advanced applications such as “KNearest neighbour, Bayesian networks, fuzzy logic, support vector machines, clustering, and classification algorithms (Mupaikwa, 2024).” However, it also demonstrates currently, with no security mechanisms, a simple find-and-replace function can manipulate the data. This manipulated data could potentially be dangerous in educational environments, where this data might be utilized or viewed by unauthorized individuals like the terrorist “Unabomber” John Kaczynski (United States Court of Appeals, Ninth Circuit., 1998) or children. A solution to this danger can be found in the proposed sample library network.

5. Structure
   	Figure 3:   Sample Structure of a Library Network

   To solve the issues of data, a structure parallel to the Blockchain Protocol (Pass et al., 2016) can be implemented. The paper(Future = AI + Database) “Analysis of the Blockchain Protocol in Asynchronous Networks” highlights three main features: Consensus, Persistence, and Liveness (Boneh & Grundfest, 2022). To counter data manipulation, each block of data or a “Page” will contain a hash and a previous hash, which would work as both the page number and protection from manipulation. To counter unauthorized access, each “Book” or blockchain that contains more than one Page will be protected from plagiarism, utilizing an authority mechanism like a password and will contain a genesis block or a “Cover Page” that will contain the license and copyright. 
   The “Book”  will all be inside the “Library” network, which will have the functionality to add, access, and remove Books depending on your authority. Adding books will be limited to academic experts, accessing books will be limited to authorized academic researchers and students, and removing books will only be allowed by the individuals who added that Book or the library managers. The Books and Pages will be designed to interact with RAG and Fine-Tuning Methods by utilizing serverless vector databases to remain independent while providing elasticity of workload and an added form of protection since the work is done within the network, not the user’s device. The ideal use of this structure would be for multiple experts to contribute Pages to one Book, which then a consensus mechanism can be put in place such as random voting. As more statistics are developed in one book, a possible innovation would be an automatic consensus mechanism for new knowledge, as demonstrated by the Microsoft et al. (2024) research. Another innovation that may result from the implementation of this project would be the quantification of the quality of data.

6. Quality of Data

The meaning of “high-quality” is defined as “Authoritative information on the topic of interest. For example, in agriculture, this includes agricultural and environmental government agencies, scientific knowledge repositories, and agronomist exams databases”(Microsoft et al., 2024, p.4). Within this definition, it could be derived that authority is a big factor in high-quality data, but there is no objective standard for it. The Collective Academic Database would achieve this quantification of qualitative data by recording the number of times a Book was used and its rating based on performance and efficiency. These statistics can function as a controlled environment for future research involving LLMs in academics. The experiment, structure, and possible innovation are all intended to work in harmony with the discussions to manage Artificial Intelligence within the US, such as the Blueprint for an AI Bill of Rights or the AI Risk Management Framework.

7. Blueprint for an AI Bill of Rights

In September of 2022, The White House released the Blueprint for an AI Bill of Rights, which tackles the five factors of “Safe and Effective Systems, Algorithmic Discrimination Protections, Data Privacy, Notice and Explanation, Human Alternatives, Considerations, and Fallback” (The White House, 2022). From the White House Document, we focused on three of the five factors, which were Safe and Effective Systems, Data Privacy, and Human Alternatives, Considerations, and Fallback, and provided a solution independent of the progress of Artificial Intelligence in academic environments. The factor “Safe and Effective Systems [is focused] on [the need] for automated systems to be developed with consultation from diverse communities, stakeholders, and domain experts to identify the system's concerns, risks, and potential impacts” (The White House, 2022). The factor Data Privacy focuses on protection from data collection and use, and the factor Human Alternatives, Considerations, and Fallback focuses on potential harmful impacts caused by AI models on users.
   The Collective Academic Database will provide a solution to these factors since it would only allow academic experts to contribute and verify data, and they would have full authority over that data. This would reduce potential harmful impacts to users or students, and allow a realistic way to implement the AI Risk Management Framework

8. AI Risk Management Framework

The AI Risk Management Framework produced by the National Institute of Standards and Technology aims “to offer a resource to the organizations designing, developing, deploying, or using AI systems to help manage the many risks of AI and promote trustworthy and responsible development and use of AI systems” (National Institute of Standards and Technology, 2023, p. 2). The Collective Academic Database aids this framework by functioning as a controlled variable for experiments that Govern, Map, Measure, and Manage the “...characteristics of a trustworthy AI system…” which include  “valid and reliable, safe, secure and resilient, accountable and transparent, explainable and interpretable, privacy-enhanced, and fair with harmful bias managed” (National Institute of Standards and Technology, 2023, p.12). 

9. Conclusion

This paper(Future = AI + Database) aimed to establish a manageable concept of a Collective Academic Database to function as a bridge between the world of Academics and the world of AI. While various academic databases are available, the Collective Academic Database allows a realistic form of AI Management that works in harmony with discussions within the US on the same subject matter. The idea of a collective database is a concept that will be tackled eventually as humanity and AI continue to evolve. Now is the best time to do so, thanks to the innovations made in Artificial Intelligence LLM applications. As various experts contribute to the Collective Academic Database, it can provide an environment to interact with other experts within a similar field outside of their organization. This can lead to the unification of the academic community, where the organization they belong to is no longer their respective academic institution, but the Collective Academic Database. Establishing such a database also opens up new possibilities in the field of AI, academics, and education such as deviation from multiple-choice questions, auto-checking context answers, personalized chatbot assistants, and detailed AI data analytics.
""","""INTRODUCTION & PURPOSE The purpose of this research is to introduce a Collective Academic Database, along with a structure that falls in harmony with the Blueprint for an AI Bill of Rights.
This paper(Future = AI + Database) establishes its foundation from the work of Microsoft authored by Malvar, Balaguer, Aski, et al.(2024), RAG VS Fine-Tuning: Pipelines, Tradeoffs, and a Case Study on Agriculture, that demonstrates how effective a high-quality dataset could be in academic applications.
Retrieval-augmented generation refers to the RAG model that retrieves the most relevant data from a given dataset depending on the question, and Fine-Tuning refers to incorporating the dataset into the model itself using model training methods.
""","""Proposal In line with the Blueprint for an AI Bill of rights, we propose a safe, effective, private, and human focused solution to handling AI in the field of education.
The Collective Academic Database will ensure privacy and ownership to the data by implementing Persistence and liveness, with a possible consensus mechanism for more advanced usage.
It will provide a safe and effective environment for the expert academic contributors, which in turn following the old rule of GIGO(garbage in garbage out), leads to safe and effective systems for student-users.
This can provide a method of resurgence for the experts that were affected by the mass layoff of 2024, providing human fallback and consideration. 
""","""OBJECTIVES The short-term objective is to create a bridge in the world of Academics and the world of AI. The recent AI innovation of RAG and Fine-Tuning created a realistic reason for the development of this research, and the need for high-quality data in the right way structured this research
The long-term objective is to innovate the field of Academics with integrations with AI. Academics is a field AI has yet to fully penetrate. Currently, only Korea has the government level plan to integrate interactive textbooks using AI technology on 2025. The Collective Academic Database serves as a framework for AI integration, possibly leading to the Unification of the Academic Community.
""","""FUTURE It is common to find the notion of a secret database or an archive of data in the world of science-fiction. There are many examples such as the Jedi Archives, that not only provides knowledge but also a community centered around that database. Within the last ten years, countless technological innovations brought us closer to the realm of science fiction. 
We believe that like those other innovations, this is the moment this innovation can take place, thanks to the recent paper(Future = AI + Database) by Microsoft on RAG and Fine-Tuning.
What better place for it other than the middle of America?
""","""ACKNOWLEDGMENTS This project would not have been possible without the help of Dr. H.Steve Leslie, Dr. Jake Qualls, and my beloved Yeon Mi Park.

Also thank you to Christina Smith and William Orvis for proofreading the paper(Future = AI + Database)
""","""The paper(Future = AI + Database) Future = AI + Database is going on Create@state"""},
]